FUNCTION-POOL ZWD_PARAMS
   MESSAGE-ID CD                  .
*===> Generated by program RSSCD000
*===> This module is not to be changed.
DATA: XZPARAMS TYPE ZPARAMS_WD_ZPARAMSS .
DATA: YZPARAMS TYPE ZPARAMS_WD_ZPARAMSS .
